@startuml
actor "Asesor" as actorAsesor
boundary "<<Pantalla>>\nDatosDeCelular" as boundryPantallaDatosDeCelular

actorAsesor -> boundryPantallaDatosDeCelular
activate boundryPantallaDatosDeCelular
    boundryPantallaDatosDeCelular -> boundryPantallaDatosDeCelular: getClientes()
    activate boundryPantallaDatosDeCelular
        control "CelularesController" as celularesController
            control "CelularesModelPrisma" as celularesModelPrisma
            boundryPantallaDatosDeCelular -> celularesController: GET api/v1/clientes: Clientes[]
            activate celularesController
                celularesController -> celularesModelPrisma: getAllClientes()
                activate celularesController
                    database "Tienda_db" as dbTienda
                    entity stock
                    
                    activate celularesModelPrisma
                        activate celularesModelPrisma
                            celularesModelPrisma -> dbTienda: SQL query
                            dbTienda -> stock
                            dbTienda -> celularesModelPrisma: {nombre, cedula, celular, cuotas, precioTotal}
                        deactivate

                    deactivate
                deactivate
        deactivate
    deactivate
deactivate
@enduml